<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ns_cookies"
 *
 * Auto generated by Extension Builder 2019-11-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '[NITSAN] Ns Cookies',
    'description' => '',
    'category' => 'plugin',
    'author' => '',
    'author_email' => '',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.0.0-10.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
